version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  test:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn run test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  deployToDev:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
            fingerprints:
              - 35:3f:1a:4f:50:b4:00:a4:36:79:da:41:44:06:6e:7c
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn run build
      - run: scp -o StrictHostKeyChecking=no -r ./build/* ubuntu@ec2-54-196-34-99.compute-1.amazonaws.com:/var/www/html

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  deployToNFS:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
            fingerprints:
              - 35:3f:1a:4f:50:b4:00:a4:36:79:da:41:44:06:6e:7c
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn run build
      - run: scp -o StrictHostKeyChecking=no -r ./build/* ubuntu@ec2-3-94-81-82.compute-1.amazonaws.com:/mnt/sharedfolder
      - run: ssh -o StrictHostKeyChecking=no ubuntu@ec2-54-81-68-200.compute-1.amazonaws.com 'sudo service apache2 restart'
      - run: ssh -o StrictHostKeyChecking=no ubuntu@ec2-3-231-148-96.compute-1.amazonaws.com 'sudo service apache2 restart'
      - run: ssh -o StrictHostKeyChecking=no ubuntu@ec2-54-90-119-157.compute-1.amazonaws.com 'sudo service nginx restart'

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
    

workflows:
  version: 2
  normal_run:
    jobs:
      - build: 
          filters:
            branches:
              only:
                - master
      
      - deployToDev:
          requires:
            - build
            
          filters:
            branches:
              only:
                - master
      - request-testing:
          type: approval
          requires:
            - deployToDev
            
      - deployToNFS:
          requires:
            - request-testing
          filters:
            branches:
              only:
                - master


  

      